export const countryNameMappings: Record<string, string> = {
  English: "England",
  Italian: "Italy",
  Spanish: "Spain",
  Brazilian: "Brazil",
  French: "France",
  Swiss: "Switzerland",
  Colombian: "Colombia",
  Cypriot: "Cyprus",
  Czech: "Czech-Republic",
  German: "Germany",
  Danish: "Denmark",
  Ecuadorian: "Ecuador",
  NorthernIrish: "Northern-Ireland",
  Scottish: "Scotland",
  Welsh: "Wales",
  Greek: "Greece",
  Hungarian: "Hungary",
  Irish: "Ireland",
  Japanese: "Japan",
  Chinese: "China",
  Chilean: "Chile",
  Mexican: "Mexico",
  Austrian: "Austria",
  Belgian: "Belgium",
  Bulgarian: "Bulgaria",
  World: "World",
  USA: "USA",
  Portuguese: "Portugal",
  Polish: "Poland",
  Swedish: "Sweden",
  Slovakian: "Slovakia",
  SouthAfrican: "South-Africa",
  SaudiArabian: "Saudi-Arabia",
  Singaporean: "Singapore",
  Turkish: "Turkey",
  Argentine: "Argentina",
  Australian: "Australia",
  African: "Mali",
  European: "Europe",
  SouthAmerican: "Uruguay",
  Dutch: "Netherlands",
  "Northern Irish": "Northern-Ireland",
  Norwegian: "Norway",
  Peruvian: "Peru",
  "Saudi Arabian": "Saudi-Arabia",
  "South African": "South-Africa",
};
