export const teamNameMappings: Record<string, string> = {
  "Austria Wien": "Austria Vienna",
  Hartberg: "TSV Hartberg",
  "Rheindorf Altach": "SCR Altach",
  "Blau-Weiß Linz": "FC BW Linz",
  "WSG Tirol": "WSG Wattens",
  "LASK Linz": "Lask Linz",
  "Rapid Wien": "Rapid Vienna",
  "Austria Klagenfurt": "Austria Klagenfurt",
  "Red Bull Salzburg": "Red Bull Salzburg",
  "Sturm Graz": "Sturm Graz",
  "Wolfsberger AC": "Wolfsberger AC",
  "Grazer AK": "Grazer AK",

  //For England
  "Newcastle United": "Newcastle",
  "Man United": "Manchester United",
  "Nottingham Forest": "Nottingham Forest",
  "Ipswich Town": "Ipswich",
  "Tottenham Hotspur": "Tottenham",
  "Southampton FC": "Southampton",
  "Liverpool FC": "Liverpool",
  "Wolverhampton Wanderers": "Wolves",
  Wolverhampton: "Wolves",
  "Fulham FC": "Fulham",
  "AFC Bournemouth": "Bournemouth",
  "Leicester City": "Leicester",
  "Arsenal FC": "Arsenal",
  "Aston Villa": "Aston Villa",
  "Brentford FC": "Brentford",
  "Crystal Palace": "Crystal Palace",
  "Brighton & Hove Albion": "Brighton",
  "Brighton and Hove Albion": "Brighton",
  "Man City": "Manchester City",
  "Chelsea FC": "Chelsea",
  "West Ham United": "West Ham",
  "Everton FC": "Everton",
};
